### ISSUE TITLE
file.zip automatically starts downloading.

### ISSUE THREAD

**Issue by abdulrehmanch112** [calvinmetcalf/leaflet.shapefile#11] opened 2014-07-05 15:49 UTC
I want to prevent it from downloading...

**Comment by calvinmetcalf** [comment] 2014-07-05 15:51
Can you be a little more specific?

**Comment by abdulrehmanch112** [comment] 2014-07-05 16:04
![shp](https://cloud.githubusercontent.com/assets/8075814/3487006/f6820b02-045d-11e4-8c8f-aa1a71e53fc2.PNG)

**Comment by abdulrehmanch112** [comment] 2014-07-05 16:05
and this problem preventing shape file to show on map.

**Comment by calvinmetcalf** [comment] 2014-07-05 16:14
that part I got , what action did you do that led to this behavior.

**Comment by abdulrehmanch112** [comment] 2014-07-05 18:22
i ve stopped idm to moniter my site "Donot Download from this Link." but its not proper solution

**Comment by davidlukerice** [comment] 2015-05-14 20:06
So you visit your site that's loading a shape.zip file into leaflet, and instead of loading it into the map, the browser tries to download it to your computer?

**Comment by ogazyben** [comment] 2017-03-14 22:51
Yes, I have the same issue, instead of loading it into map the browser tries to download it to my computer

**Comment by calvinmetcalf** [comment] 2017-03-15 11:05
is the webserver sending it as an attachment ?

**Comment by ogazyben** [comment] 2017-03-15 11:33
Yes

**Comment by calvinmetcalf** [comment] 2017-03-15 14:15
I'm not sure if there is anything this library can do about the browser behavior like that

**Comment by ogazyben** [comment] 2017-03-15 23:42
Thanks a lot. I am trying to show a large parcel data in a shapefile format on my map. Small size parcel data works fine using the shapefile plugin but it responds slowly and often takes a long time to draw or don't draw at all.Please Do you have any suggestions as to the best way to display the data on my map? I have tried GeoJson but it also responded slowly.

**Comment by calvinmetcalf** [comment] 2017-03-16 12:29
the more data you have the more work it is for the browser to render it, you could look into something like carto.com or mapbox which are services to help display larger data sets or you could try to cut tiles

**Comment by calvinmetcalf** [comment] 2017-03-16 12:30
closing as we solved the issue of the files downloading

**Closed as completed by calvinmetcalf** 2017-03-16 12:29 UTC

**Comment by lalprakash** [comment] 2017-05-31 16:56
@calvinmetcalf I'm also facing this issue. I'm using leaflet.shapefile to display a shapefile in my map. The shapefile just downloads by default instead of displaying in the map. 

I'm adding the shapefile as below

```
var shpfile = new L.Shapefile('path_to_zip_file/file.zip'); 
shpfile.addTo(map);
```

Isnt't it the right way to add the shapefile?

**Comment by calvinmetcalf** [comment] 2017-05-31 17:08
it's not a clientside issue @lalprakash the issue is that the server is setting a heading that tells the client 'hey you should download this thing' which is causing it to download automatically

**Comment by lalprakash** [comment] 2017-05-31 17:29
@calvinmetcalf Thank you for the response. I clearly understand what you mean. But I just cant figure out where in my code or in my server has I written "hey you should download this thing". If possible please suggest me a way so that I can change "hey you should download this thing" to "hey you should NOT download this thing".

**Comment by calvinmetcalf** [comment] 2017-05-31 18:43
depending on your server it could be the default behavior for zips

**Comment by lalprakash** [comment] 2017-05-31 18:48
@calvinmetcalf  is there any suggestion from your side that has to be done in my server so that the issue is solved ?  I'm really glad and thankful to you for such a speedy response.

**Comment by calvinmetcalf** [comment] 2017-05-31 19:28
you should check the headers that the server is sending, the main this is just that the browser is downloading it it **before** it gets to this lib
